---
# ==============================================================================
# Personal Applications Installation
# ==============================================================================
#
# Install personal applications on all machines tagged with 'tag:personal'.
# This playbook targets all hosts with 'tag:personal' tag.
#
# Applications installed:
# - Browsers: Brave
# - Communication: Slack, Discord
# - Development: VS Code, PyCharm Pro, GoLand, DataGrip, DataSpell, Beekeeper Studio
# - Productivity: Obsidian, OnlyOffice
# - Utilities: Termius, Syncthing, Transmission
#
# Use case:
# - Sync same tools across all personal devices (laptop, workstation, etc.)
# - Independent of environment (dev/prod)
#
# Prerequisites:
# - Host must have 'tag:personal' in Tailscale
# - Ubuntu/Debian-based system with snap support
#
# Usage:
#   ansible-playbook personal.yml                    # Install all applications
#   ansible-playbook personal.yml --limit workstation  # Install on specific host
#   ansible-playbook personal.yml --check            # Dry run
#
# Verify installation:
#   snap list
#
# ==============================================================================

- name: Install Personal Applications
  hosts: personal  # All hosts with tag:personal
  become: false
  gather_facts: true

  vars:
    # Snap packages to install
    # Classic mode is required for some snaps (mostly JetBrains IDEs and VS Code)
    snap_packages:
      # Browsers
      - name: brave
        classic: false

      # Communication
      - name: slack
        classic: false
      - name: discord
        classic: false

      # Development - Editors/IDEs
      - name: code
        classic: true

      # Development - JetBrains
      - name: pycharm-professional
        classic: true
      - name: goland
        classic: true
      - name: datagrip
        classic: true
      - name: dataspell
        classic: true

      # Development - Database Tools
      - name: beekeeper-studio
        classic: false

      # Productivity
      - name: obsidian
        classic: false
      - name: onlyoffice-desktopeditors
        classic: false

      # Utilities
      - name: termius-app
        classic: false
      - name: syncthing-arubislander
        classic: false
      - name: transmission
        classic: false

  pre_tasks:
    - name: Cache become password from Bitwarden
      ansible.builtin.set_fact:
        ansible_become_pass: "{{ lookup('bitwarden.secrets.lookup', '779003f3-0ecb-4ad0-b5bc-b38a012e4931', base_url='https://vault.bitwarden.eu') }}"
      no_log: true
      tags: [always]

    - name: Display deployment info
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Installing Personal Applications"
          - "=========================================="
          - "Hostname: {{ inventory_hostname }}"
          - "Tailscale IP: {{ ansible_host }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Total packages: {{ snap_packages | length }}"
          - "=========================================="
      tags: [always]

    - name: Verify host has required tags
      ansible.builtin.assert:
        that:
          - "'personal' in group_names"
        fail_msg: "Host must have 'tag:personal' in Tailscale."
      tags: [always]

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      tags: [always]

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
      become: yes
      tags: [always]

    - name: Ensure snapd service is running
      ansible.builtin.systemd:
        name: snapd
        state: started
        enabled: yes
      become: yes
      tags: [always]

    - name: Wait for snapd to be ready
      ansible.builtin.command: snap wait system seed.loaded
      changed_when: false
      become: yes
      tags: [always]

    - name: Install snap packages
      community.general.snap:
        name: "{{ item.name }}"
        classic: "{{ item.classic }}"
        state: present
      become: yes
      loop: "{{ snap_packages }}"
      loop_control:
        label: "{{ item.name }}"
      tags: [install]
      register: snap_installs

    - name: Get list of installed snaps
      ansible.builtin.command: snap list
      register: snap_list
      changed_when: false
      tags: [verify]

  post_tasks:
    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - ""
          - "╔════════════════════════════════════════════════════════════╗"
          - "║      Personal Applications Installed Successfully          ║"
          - "╚════════════════════════════════════════════════════════════╝"
          - ""
          - "Host: {{ inventory_hostname }}"
          - "Tailscale IP: {{ ansible_host }}"
          - ""
          - "Installed Snap Packages:"
          - "{{ snap_list.stdout }}"
          - ""
          - "Applications installed ({{ snap_packages | length }} total):"
          - "  Browsers: brave"
          - "  Communication: slack, discord"
          - "  Development: code, pycharm-professional, goland, datagrip, dataspell"
          - "  Database: beekeeper-studio"
          - "  Productivity: obsidian, onlyoffice-desktopeditors"
          - "  Utilities: termius-app, syncthing-arubislander, transmission"
          - ""
          - "Launch applications:"
          - "  - From application menu (search for app name)"
          - "  - Or from terminal: brave, slack, discord, code, etc."
          - ""
          - "Verify installations:"
          - "  snap list"
          - "  snap list | grep <package-name>"
          - ""
          - "Update all snaps:"
          - "  sudo snap refresh"
          - ""
      tags: [always]
